// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZvaFlc-QucEMU_YonDbZQjGdxq_fAJo',
    appId: '1:905334305653:web:e9a4f82420591481c1193c',
    messagingSenderId: '905334305653',
    projectId: 'fresh-mart-1db2c',
    authDomain: 'fresh-mart-1db2c.firebaseapp.com',
    storageBucket: 'fresh-mart-1db2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEsj_wqKIx5qUkHH6Hk3HF4LiWMACs0xY',
    appId: '1:905334305653:android:f0ddc5710f90f8d3c1193c',
    messagingSenderId: '905334305653',
    projectId: 'fresh-mart-1db2c',
    storageBucket: 'fresh-mart-1db2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfKFnKtJUolq8rRWraqVyDzSvSww1IPmo',
    appId: '1:905334305653:ios:f23136f605091680c1193c',
    messagingSenderId: '905334305653',
    projectId: 'fresh-mart-1db2c',
    storageBucket: 'fresh-mart-1db2c.appspot.com',
    iosClientId: '905334305653-52jrnpvhd44472p1r8teobcho5mnraet.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfKFnKtJUolq8rRWraqVyDzSvSww1IPmo',
    appId: '1:905334305653:ios:f23136f605091680c1193c',
    messagingSenderId: '905334305653',
    projectId: 'fresh-mart-1db2c',
    storageBucket: 'fresh-mart-1db2c.appspot.com',
    iosClientId: '905334305653-52jrnpvhd44472p1r8teobcho5mnraet.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshMart',
  );
}
